from django.core.management.base import BaseCommand
from dictionnaire.models import MotRacine

# 📌 Liste des 100 mots Hassaniya avec leur traduction en français
mots_racines = [
    ("أركاج", "personne"),
    ("إشير", "enfant"),
    ("آنزي", "Chemin"),
    ("آبروخ", "Pluie"),
    ("أسلاي", "Grande tasse"),
    ("آدرس", "Spécial pour le lait Label"),
    ("أزز", "Rapide"),
    ("أسكره", "Fenêtre"),
    ("أفكراش", "le meiller"),
    ("آمروك", "Lion"),
    ("إيكيلو", "Étoile"),
    ("إيريفي", "Rivière"),
    ("ألجلاج", "La rigueur du froid"),
    ("آوراغ", "Hcl"),
    ("آسواغ", "Marché"),
    ("آجلاج", "Colère"),
    ("آمسكري", "refiser"),
    ("إمغني", "Chanteur"),
    ("أزوان", "Musique"),
    ("آزاي", "Pays"),
    ("اشور", "Soleil"),
    ("اتافلويت", "Corde"),
    ("اتيدينيت", "Patience"),
    ("آردين", "Ombre"),
    ("إيكاون", "Groupe"),
    ("تيكادرين", "Lac"),
    ("التيدوم", "arbre"),
    ("تاطرارت", "végétation"),
    ("آكلال", "Ciel"),
    ("زوزاي", "Petit"),
    ("تيشلاط", "Outil"),
    ("أشكراف", "Menottes et pieds"),
    ("اتزكنين", "Silence"),
    ("إكندي", "Chaleur"),
    ("آزعاف", "Danger"),
    ("أفلجيط", "Couteau"),
    ("تيكفيت", "végétation"),
    ("تيدكت", "Farine de viande"),
    ("تغليت", "Transplantation"),
    ("تغيه", "végétation"),
    ("تيدشمه", "végétation"),
    ("أكنات", "Fruit"),
    ("ابكاك", "Fleur"),
    ("توكه", "Fruit arbre"),
    ("إيمجيج", "Compagnon"),
    ("أيزن", "Lait"),
    ("أبيله", "Honneur"),
    ("إنيتي", "Lumière"),
    ("آز", "Air"),
    ("تادريصه", "Outil"),
    ("أوروار", "Départ"),
    ("اصكاكيط", "Cloche"),
    ("اكرور", "jeu"),
    ("الكارور", "Fruit"),
    ("ازفطي", "mensonge"),
    ("اتغشمي", "Refuge"),
    ("البلكه", "Collier"),
    ("آوداش", "Grand taureau"),
    ("آفوك", "Paix"),
    ("امكاي", "Égalité"),
    ("آزلاي", "Doute"),
    ("امكركط", "Avancement"),
    ("آكرط", "Éclat"),
    ("تيكط", "Guerre"),
    ("أيبار", "Harmonie"),
    ("تاوكت", "Courage"),
    ("تنكاكه", "Solidité"),
    ("مندريش", "Rêve"),
    ("آغرشي", "Force"),
    ("تابلنكه", "Découverte"),
    ("بديزوك", "Départ"),
    ("كرفاف", "Chapeau"),
    ("أزغر", "Petit"),
    ("اتيكيت", "Savoir-vivre"),
    ("اجونكيه", "Respect"),
    ("أدرك", "Atteindre"),
    ("تيلكه", "Cette"),
    ("آشباش", "Vêtements"),
    ("تيمشي", "Marcher"),
    ("امتينك", "Forte"),
    ("ازكار", "Mémoire"),
    ("ازكال", "Clair"),
    ("آفلال", "Doux"),
    ("تيدمكي", "Ancien"),
    ("اسنباي", "Connaissance"),
    ("أويال", "Écoute"),
    ("ازوزال", "Bruit"),
    ("ادرماز", "Guerrier"),
    ("أفرطاص", "Découpe"),
    ("اكطاطي", "Survie"),
    ("اتبيب", "Médecin"),
    ("أدباي", "Poète"),
    ("تيجكريت", "Sagesse"),
    ("تاسدبيت", "Protection"),
    ("تيشيت", "Ville"),
    ("تشليت", "Présence"),
    ("آمرش", "Retour"),
    ("اتوكرنيت", "Patience"),
    ("تامورت", "Terre"),
    ("أجار", "Frontière"),
    ("آغوج", "Montagne"),
    ("تيارت", "Chameau"),
    ("آكنان", "Riche"),
    ("آفطوط", "Rivière"),
]

class Command(BaseCommand):
    help = "Importe les 100 mots Hassaniya avec leurs traductions"

    def handle(self, *args, **kwargs):
        for mot, traduction in mots_racines:
            mot_obj, created = MotRacine.objects.get_or_create(nom=mot, defaults={"traduction": traduction})
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Mot ajouté : {mot} - {traduction}"))
            else:
                self.stdout.write(self.style.WARNING(f"⚠ Mot existant : {mot} - {mot_obj.traduction}"))
